/***********************************************************************/
/*                                                                     */
/*  FILE        :action.c	                                           */
/*  DATE        :Tue, Sep 27, 2011                                     */
/*  DESCRIPTION :Reset Program                                         */
/*  CPU TYPE    :SH7125                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
//ÉçÉ{ÉbÉgÇÃìÆçÏ
#include "global.h"

void action(int number){
	switch(number){
	case 1:

	break;
	case 2:
	
	break;
	case 3:
	
	break;
	case 4:
	
	break;
	case 5:
	
	break;
	case 6:
	
	break;
	case 7:
	
	break;
	case 8:
		
	break;
	}	
}


void delay_ms(int ms)
{
	int i=0;
	for(i=0;i<ms*25000;i++){}
}