/***********************************************************************/
/*                                                                     */
/*  FILE        :basic_servo_class.h                                   */
/*  DATE        :Tue, Sep 27, 2011                                     */
/*  DESCRIPTION :Definition of Vector                                  */
/*  CPU TYPE    :SH7125                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
//basic_servoクラスの構成
//すべてのサーボに出される命令
				  
class basic_servo{
	public:
		void home_position();
		void all_servo_move();
		void all_servo_on();
		void all_servo_off();
};