/***********************************************************************/
/*                                                                     */
/*  FILE        :basic_servo_class.cpp		                           */
/*  DATE        :Tue, Sep 27, 2011                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :SH7125                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
//basic_servoÉNÉâÉXÇÃíÜêg

#include "global.h"
#include "basic_servo_class.h"
#include "iodefine.h"

void basic_servo::home_position()
{
	SCI0_OUT_DATA_ID((char)254);
	SCI0_OUT_DATA_NORMAL((char)83);

	sci0_miss=0;
	sci0_wait=0;
}

void basic_servo::all_servo_move()
{
	SCI0_OUT_DATA_ID(0xFE);
	SCI0_OUT_DATA_NORMAL(58);

	sci0_miss=0;
	sci0_wait=0;
}

void basic_servo::all_servo_on()
{
	SCI0_OUT_DATA_ID((char)254);
	SCI0_OUT_DATA_NORMAL((char)89);	

	sci0_miss=0;
	sci0_wait=0;
}

void basic_servo::all_servo_off()
{
	SCI0_OUT_DATA_ID(0xFE);
	SCI0_OUT_DATA_NORMAL(90);	

	sci0_miss=0;
	sci0_wait=0;
}
