/***********************************************************************/
/*                                                                     */
/*  FILE        :class_setup.cpp			                           */
/*  DATE        :Tue, Sep 27, 2011                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :SH7125                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
//ÉNÉâÉXÇÃêÈåæ

#include "global.h"
#include "servo_class.h"
#include "basic_servo_class.h"

void class_setup()
{

}