/***********************************************************************/
/*                                                                     */
/*  FILE        :Serial.h                                              */
/*  DATE        :Tue, Sep 27, 2011                                     */
/*  DESCRIPTION :Definition of Vector                                  */
/*  CPU TYPE    :SH7125                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
//defineしているもの

//spicyberry_cplus_ver1_0.cpp
#define PC_COMMAND	0
#define K_L2        0x0001 // L2
#define K_R2        0x0002 // R2
#define K_L1        0x0004 // L1
#define K_R1        0x0008 // R1
#define K_RU        0x0010 // △
#define K_RR        0x0020 // ○
#define K_RD        0x0040 // ×
#define K_RL        0x0080 // □
#define K_SEL        0x0100 // SELECT
#define K_ST        0x0200 // START
#define K_R3        0x0400 // 右アナログPUSH
#define K_L3        0x0800 // 左アナログPUSH
#define K_LU        0x1000//0x0010 // ↑
#define K_LR        0x2000 // →
#define K_LD        0x4000 // ↓
#define K_LL        0x8000 // ←
#define K_LU_R1     0x1008 // ↑→
#define K_LU_L1     0x1004 // ↑←

#define SCI0_setup			SCI0_INIT
#define SCI0_tx				SCI0_OUT_DATA_NORMAL
#define SCI0_tx_parity		SCI0_OUT_DATA_ID

#define SCI1_setup			SCI1_INIT
#define SCI1_tx				SCI1_OUT_DATA
#define SCI1_tx_parity		SCI1_OUT_DATA_PARITY
#define intSCI1_tx_buff		SCI1_OUT_DATA_FROM_BUFFER
#define SCI1_read_buff		SCI1_IN_DATA_CHECK
#define SCI1_write_buff		SCI1_WRITE_DATA
#define SCI1_tx_char		SCI1_OUT_DATA_CHAR
#define SCI1_tx_str			SCI1_OUT_DATA_STRING
#define SCI1_tx_d			SCI1_OUT_DATA_DOUBLE
#define SCI1_tx_x			SCI1_OUT_DATA_X
#define SCI1_tx_X			SCI1_OUT_DATA_BIG_X
#define SCI1_rx_char		SCI1_IN_DATA_WAIT
#define SCI1_rx_char_nowait	SCI1_IN_DATA_NOW
#define inc_buff_p1			SCI1_BUFFER_PLUS

#define SCI2_setup			SCI2_INIT
#define SCI2_tx				SCI2_OUT_DATA
#define SCI2_rx				SCI2_IN_DATA
#define intSCI2_tx_buff		SCI2_OUT_DATA_FROM_BUFFER
#define SCI2_read_buff		SCI2_IN_DATA_CHECK
#define SCI2_write_buff		SCI2_WRITE_DATA
#define SCI2_tx_char		SCI2_OUT_DATA_CHAR
#define SCI2_tx_str			SCI2_OUT_DATA_STRING
#define SCI2_tx_d			SCI2_OUT_DATA_DOUBLE
#define SCI2_tx_x			SCI2_OUT_DATA_X
#define SCI2_tx_X			SCI2_OUT_DATA_BIG_X
#define SCI2_rx_char		SCI2_IN_DATA_WAIT
#define SCI2_rx_char_nowait	SCI2_IN_DATA_NOW
#define inc_buff_p2			SCI2_BUFFER_PLUS