/***********************************************************************/
/*                                                                     */
/*  FILE        :global.h                                              */
/*  DATE        :Tue, Sep 27, 2011                                     */
/*  DESCRIPTION :Definition of Vector                                  */
/*  CPU TYPE    :SH7125                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
//global‚È‚à‚Ì         

#include <stdarg.h>

#ifdef GLOBAL_INSTANCE
#define GLOBAL 
#else
#define GLOBAL extern 
#endif

#include "define.h"
#include "sci.h"


#ifdef __cplusplus
extern "C" {
#endif

//sci0.c
GLOBAL void SCI0_INIT(int);
GLOBAL void SCI0_OUT_DATA_NORMAL(char);
GLOBAL void	SCI0_OUT_DATA_ID(char);
GLOBAL void SCI0_intpre(void);
GLOBAL void SCI0_err(void);

//sci1.c
GLOBAL void SCI1_INIT(int);
GLOBAL void SCI1_OUT_DATA(char);
GLOBAL void	SCI1_OUT_DATA_PARITY(char);
GLOBAL char SCI1_IN_DATA_CHECK(void);
GLOBAL char SCI1_WRITE_DATA(char);
GLOBAL char SCI1_OUT_DATA_CHAR(char);
GLOBAL void SCI1_OUT_DATA_STRING(char *);
GLOBAL void SCI1_OUT_DATA_DOUBLE(long);
GLOBAL void SCI1_OUT_DATA_X(long);
GLOBAL void SCI1_OUT_DATA_BIG_X(long);
GLOBAL char SCI1_IN_DATA_WAIT(void);
GLOBAL char SCI1_IN_DATA_NOW(void);
GLOBAL void SCI1_intpre(void);
GLOBAL void SCI1_err(void);
GLOBAL unsigned short SCI1_BUFFER_PLUS(unsigned short);

//sci2.c
GLOBAL void SCI2_INIT(int);
GLOBAL void SCI2_intpre(void);
GLOBAL void SCI2_err(void);
GLOBAL void SCI2_OUT_DATA(char);
GLOBAL char SCI2_rx(void);

//init.c
GLOBAL void setup(void);
GLOBAL void class_setup(void);

//action.c
GLOBAL void action(int);
GLOBAL void delay_ms(int);
GLOBAL void delay_ms_cmt(long);
//GLOBAL void walk(servo,servo);

//intterrupt.c
GLOBAL void int_cmt0_cmi0(void);

GLOBAL long cmt0_count;
GLOBAL int cmt0_flag;
#ifdef __cplusplus
}
#endif

//interrupt.c
GLOBAL void int_ad_ad0();
GLOBAL void int_sci1_txi1();
GLOBAL void int_sci2_txi2();
//GLOBAL int ad_int[8];

GLOBAL int sci0_data_get_i;
GLOBAL int Get_Byte[4];
GLOBAL int from_pc_sci[10];
GLOBAL int pc_command[10];
GLOBAL int PC_command_number;
GLOBAL int PC_command_flag;
GLOBAL int PC_move_command_flag;
GLOBAL int PC_move_command_number;
GLOBAL int sci0_miss;
GLOBAL int sci0_wait;
GLOBAL int sci0_id;
GLOBAL char PS2_command;