/***********************************************************************/
/*                                                                     */
/*  FILE        :interrupt.c                                           */
/*  DATE        :Sat, Jun 25, 2011                                     */
/*  DESCRIPTION :Initialize of Vector Table                            */
/*  CPU TYPE    :SH7125                                                */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/*	Š„‚èž‚Ý‚É‚Â‚¢‚Ä‚Í‚±‚±‚É‘‚¢‚Ä‚­‚¾‚³‚¢							   */
/***********************************************************************/

#include "global.h"
#include "iodefine.h"
#include "vect.h"
#include "sci.h"

void int_ad_ad0(void){
/*	AD0.ADCR.BIT.ADST=1;     // A/D Start
	while(AD0.ADCSR.BIT.ADF==0);
	ad_int[0]=AD0.ADDR0 >>8;
	ad_int[1]=AD0.ADDR1 >>8;
	ad_int[2]=AD0.ADDR2 >>8;
	ad_int[3]=AD0.ADDR3 >>8;
	AD0.ADCSR.BIT.ADF=0;

	AD1.ADCR.BIT.ADST=1;     // A/D Start
	while(AD1.ADCSR.BIT.ADF==0);
	ad_int[4]=AD1.ADDR4 >>8;
	ad_int[5]=AD1.ADDR5 >>8;
	ad_int[6]=AD1.ADDR6 >>8;
	ad_int[7]=AD1.ADDR7 >>8;
	AD1.ADCSR.BIT.ADF=0;
*/}

void int_cmt0_cmi0(void){
	CMT0.CMCSR.BIT.CMF  = 0;
	if(cmt0_count>0){
		cmt0_count--;
		cmt0_flag=1;
	}else if(cmt0_count==0){
		cmt0_flag=0;
	}
	CMT.CMSTR.BIT.STR0 = 1;	
}
